apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sexample-y
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8sexample-y
  template:
    metadata:
      labels:
        name: k8sexample-y
    spec:
      containers:
      - name: k8sexample-y
        image: shinomontaz/k8s_example
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8sexample-y
  labels:
    name: k8sexample-y
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    name: k8sexample-y