#include "My.h"
#include <stdbool.h>
#include <limits.h>
#include <float.h>

MyParameters createDefaultMyParameters() {
    MyParameters params = {
        .AscentCandidates = 50,
        .BackboneTrials = 0,
        .Backtracking = 0,
        .BWTSP_B = 0,
        .BWTSP_Q = 0,
        .BWTSP_L = INT_MAX,
        .CandidateSetType = ALPHA,
        .ExtraCandidateSetType = QUADRANT,
        .MTSPDepot = 0,
        .DistanceLimit = DBL_MAX,
        .Excess = 0.0,
        .ExternalSalesmen = 0,
        .ExtraCandidates = 0,
        .ExtraCandidateSetSymmetric = false,
        .Gain23Used = true,
        .GainCriterionUsed = true,
        .InitialPeriod = -1,
        .InitialStepSize = 0,
        .InitialTourAlgorithm = WALK,
        .InitialTourFraction = 1.0,
        .KickType = 0,
        .Kicks = 1,
        .TSPTW_Makespan = false,
        .MaxBreadth = INT_MAX,
        .MaxCandidates = 5,
        .CandidateSetSymmetric = true,
        .MaxSwaps = -1,
        .MaxTrials = -1,
        .MoveType = 5,
        .MoveTypeSpecial = 0,
        .MTSPMaxSize = -1,
        .MTSPMinSize = 1,
        .MTSPObjective = -1,
        .NonsequentialMoveType = -1,
        .Optimum = -DBL_MAX,
        .PatchingA = 1,
        .PatchingAExtended = false,
        .PatchingARestricted = false,
        .PatchingC = 0,
        .PatchingCExtended = false,
        .PatchingCRestricted = false,
        .POPMUSIC_InitialTour = false,
        .POPMUSIC_MaxNeighbors = 5,
        .POPMUSIC_SampleSize = 10,
        .POPMUSIC_Solutions = 50,
        .POPMUSIC_Trials = 1,
        .MaxPopulationSize = 0,
        .Precision = 100,
        .Probability = 100,
        .Recombination = IPT,
        .RestrictedSearch = true,
        .Runs = 0,
        .Salesmen = 1,
        .Scale = -1,
        .Seed = 1,
        .Special = false,
        .StopAtOptimum = true,
        .Subgradient = true,
        .SubproblemSize = 0,
        .SubproblemSpecial = SUBPROBLEM_UNDEFINED,
        .SubproblemSpecial2 = SPECIALSUBPROBLEM_UNDEFINED,
        .SubsequentMoveType = 0,
        .SubsequentMoveTypeSpecial = false,
        .SubsequentPatching = true,
        .TimeLimit = DBL_MAX,
        .TotalTimeLimit = DBL_MAX,
        .TraceLevel = 1
    };
    return params;
}