// Code generated by protoc-gen-go-scratch.
// source: FleetManager/FleetManager.proto

package FleetManager

import (
	"google.golang.org/grpc"
	"net/http"

	"gitlab.ozon.ru/platform/protobuf/protoc-gen-go-http-server/types"
)

type ScratchIntegration struct {
	FleetManagerServer
}

func NewImpl(impl FleetManagerServer) *ScratchIntegration {
	return &ScratchIntegration{impl}
}

func (s *ScratchIntegration) Register(srv *grpc.Server) {
	RegisterFleetManagerServer(srv, s)
}

func (s *ScratchIntegration) NewHTTPServer(h http.Handler) http.Handler {
	return NewHTTPServer(WithImpl(s), WithAdditionalHandler(h))
}

func (s *ScratchIntegration) SwaggerUI() http.Handler {
	return SwaggerUIHandler
}

func (s *ScratchIntegration) SwaggerJSON(options types.SwaggerOptions) http.Handler {
	SetSwaggerOptions(options)
	return SwaggerJSONHandler
}
