// Code generated by protoc-gen-go-http-server. DO NOT EDIT.
// source: FleetManager/FleetManager.proto

package FleetManager

import (
	"net/http"
)

func (s *HTTPServer) GetZone(w http.ResponseWriter, r *http.Request) {
	r, _, in, err := s.opts.cdc.ReadRequest(r)
	if err != nil {
		s.opts.cdc.WriteResponse(w, nil, err)
		return
	}
	resp, err := s.opts.srv.GetZone(r.Context(), in.(*GetZoneReq))
	s.opts.cdc.WriteResponse(w, resp, err)
}

func (s *HTTPServer) GetZones(w http.ResponseWriter, r *http.Request) {
	r, _, in, err := s.opts.cdc.ReadRequest(r)
	if err != nil {
		s.opts.cdc.WriteResponse(w, nil, err)
		return
	}
	resp, err := s.opts.srv.GetZones(r.Context(), in.(*Empty))
	s.opts.cdc.WriteResponse(w, resp, err)
}

func (s *HTTPServer) GetFleet(w http.ResponseWriter, r *http.Request) {
	r, _, in, err := s.opts.cdc.ReadRequest(r)
	if err != nil {
		s.opts.cdc.WriteResponse(w, nil, err)
		return
	}
	resp, err := s.opts.srv.GetFleet(r.Context(), in.(*Empty))
	s.opts.cdc.WriteResponse(w, resp, err)
}
