// Code generated by protoc-gen-go-http-server.
// source: FleetManager/FleetManager.proto

package FleetManager

import (
	"context"

	"github.com/shinomontaz/goexps/FleetManager/model"
)

func init() {
	defaultHTTPServerOptions.srv = &ServerImpl{}
}

type ServerImpl struct{}

func (s *ServerImpl) GetZone(ctx context.Context, req *GetZoneReq) (*GetZoneResp, error) {
	targetZone := model.GetPointZone(req.Lat, req.Long)

	if targetZone == nil {
		return &GetZoneResp{}, nil
	}
	return &GetZoneResp{ZoneId: targetZone.ID}, nil
}

func (s *ServerImpl) GetZones(ctx context.Context, req *Empty) (*GetZonesResp, error) {
	coreZones := model.GetZones()

	zones := make([]*Zone, 0, len(coreZones))
	for _, w := range coreZones {
		zones = append(zones, &Zone{
			ZoneId:  w.ID,
			GeoJson: w.GeoJson,
		})
	}

	return &GetZonesResp{Zones: zones}, nil
}

func (s *ServerImpl) GetFleet(ctx context.Context, req *Empty) (*GetFleetResp, error) {

	coreZones := model.GetFleet()

	fleet := make([]*Fleet, 0, len(coreZones))
	for _, w := range coreZones {

		fleetList := make([]*Courier, 0, len(w.Fleet))

		for _, ww := range w.Fleet {
			fleetList = append(fleetList, &Courier{Id: ww.ID, Name: ww.Name, Volume: ww.Volume})
		}

		fleet = append(fleet, &Fleet{
			ZoneId: w.ID,
			Fleet:  fleetList,
		})
	}

	return &GetFleetResp{Fleet: fleet}, nil
}
